<#include "header.ftlh">
    <div class="container">
        <div class="jumbotron jumbotron-opacity">
            <h1 class="display">Nie udało się. 😥</h1>
            <p class="lead">Podane dane są niepoprawne lub podany email jest już zajęty.</p>
            <hr class="my-4">
            <a class="btn btn-primary btn-lg btn-dark" href="add-user.html" role="button">Spróbuj ponownie</a>
        </div>
    </div>
<#include "footer-jquery.ftlh">