<html>
<head>
    <meta charset="UTF-8">
    <title>JBusters</title>
    <!-- Bootstrap core CSS -->
    <link href="../../css/bootstrap.min.css" rel="stylesheet">
    <link href="../../css/style.css" rel="stylesheet">

    <!-- Google -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://apis.google.com/js/platform.js" async defer></script>
    <script src="https://apis.google.com/js/client.js" async defer></script>
    <meta name="google-signin-scope" content="profile email">
    <meta name="google-signin-client_id">

    <!-- ClockPicker Stylesheet -->
    <link rel="stylesheet" type="text/css" href="css/bootstrap-clockpicker.min.css">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
</head>
<body>
<div class="wrap">
    <header>
        <div class="container-fluid">
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                <a class="navbar-brand" href="index.html">JBusters</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item active">
                            <a class="nav-link" href="/index.html">Home </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/load-city">Wyceń mieszkanie</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/upload-file">Załaduj plik <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/my-flats">Moje mieszkania</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/add-user-form">Załóż konto</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/select-login-form">Zaloguj </a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
    </header>
