<#include "header.ftlh" >

        <div class="container">
            <div class="jumbotron jumbotron-opacity">
                <h1 class="display-4">Myślisz o sprzedaży mieszkania?</h1>
                <p class="lead">Skorzystaj z naszej wyceniarki i sprawdż ile może być warte</p>
                <hr class="my-4">
                <a class="btn btn-primary btn-lg btn-dark" href="/new-transaction" role="button">Wyceń mieszkanie</a>
            </div>
        </div>

<#include "footer.ftlh">

