<#include "header.ftlh">
    <div class="container">
        <div class="jumbotron jumbotron-opacity">
            <h1 class="display-4">Sesja wygasła.... 😥</h1>
            <p class="lead">Musisz zalogować się ponownie.</p>
            <hr class="my-4">
            <a class="btn btn-primary btn-lg btn-dark" href="login-user.html" role="button">Zaloguj ponownie</a>
        </div>
    </div>

<#include "footer-jquery.ftlh">