<html>
<head>
    <meta charset="UTF-8">
    <title>JBusters</title>
    <!-- Bootstrap core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/style.css" rel="stylesheet">
</head>
<body>
<div class="wrap">
    <header>
        <div class="container-fluid">
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                <a class="navbar-brand" href="index.html">JBusters</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item active">
                            <a class="nav-link" href="/index.html">Home <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/load-city">Wyceń mieszkanie</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="uploadFile.html">Załaduj plik</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/my-flats">Moje mieszkania</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="add-user.html">Załóż konto</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="login-user.html">Zaloguj</a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
    </header>

    <div class="container">
        <div class="jumbotron jumbotron-opacity">
            <h1 class="display-4">Wylogowano</h1>
            <p class="lead">Zapraszamy ponownie...</p>
            <hr class="my-4">
            <a class="btn btn-primary btn-lg btn-dark" href="index.html" role="button">Strona główna</a>
        </div>
    </div>
</div>
<footer>&copy; 2018 JBusters</footer>

<script src="js/jquery-3.3.1.slim.min.js"></script>
<script src="js/bootstrap.min.js"></script>

</body>
</html>