<#include "header.ftlh">
    <div class="container">
        <div class="jumbotron jumbotron-opacity">
            <h1 class="display-4">Nie udało się. 😥</h1>
            <p class="lead">Podałeś niepoprawny email lub hasło...</p>
            <hr class="my-4">
            <a class="btn btn-primary btn-lg btn-dark" href="form-login.html" role="button">Spróbuj ponownie</a>
        </div>
    </div>




</div>
<footer>&copy; 2018 JBusters</footer>
<script src="js/jquery-3.3.1.slim.min.js"></script>
<script src="js/bootstrap.min.js"></script>
</body>
</html>