<#include "include-user-header.ftlh">
    <div class="container">
        <br><br>

        <div class="jumbotron jumbotron-opacity">

            <div class="row">
                <div class="col-8">
                    <h1 class="display-4">📃🖊️</h1>
                    <p class="lead">Zapisano</p>
                    <form method="get" action="/show-transaction">
                        <button type="submit" class="btn btn-primary">OK</button>
                    </form>
                </div>

<#include "include-user-info.ftlh">

            </div>

            <hr class="my-4">
        </div>

    </div>

</div>
</div>
<#include "include-user-footer.ftlh">


