<#include "header.ftlh">

<div class="container">
        <div class="jumbotron jumbotron-opacity">
            <h1 class="display-4">Wartość twojego mieszkania to:</h1>
            <h1 id="price" class="display-4">${cena}zł </h1><h1>za m<sup>2</sup></h1>
            <hr class="my-4">
            <a class="btn btn-primary btn-lg btn-dark" href="#" role="button">Zapisz mieszkanie</a>
        </div>
    </div>

<#include "footer.ftlh">